name: Build LaTeX Document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: PhDThesis.tex
          working_directory: phdthesis/
          latex_compiler: latexmk
          latex_compiler_arguments: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
          system_packages: "gcc"
          pre_task: 'echo "''Hello, World!'' from BEFORE compilation."'
          post_task: 'echo "''Hello, World!'' from AFTER compilation."'
